-- 20260628180000_create_salon_covers_bucket.sql
-- Creates the salon-covers storage bucket and sets appropriate RLS policies.
--
-- WHY THIS IS NEEDED:
--   The portfolio upload pipeline was fixed to use signed URLs (generated by the
--   backend's service-role key) so RLS is bypassed for the actual upload.
--   However, the salon-covers bucket must physically EXIST in Supabase Storage
--   for createSignedUploadUrl() to succeed. Without this bucket, the backend
--   throws InternalServerErrorException("Bucket not found") and the mobile app
--   shows "L'upload de l'image a échoué."
--
-- UPLOAD ARCHITECTURE (signed-URL pattern, bypasses RLS):
--   1. Mobile  → POST /salons/:id/cover/upload-url  (NestJS, service role)
--   2. Backend → storage.createSignedUploadUrl('salon-covers', path)
--   3. Mobile  → storage.uploadToSignedUrl(storagePath, token, blob)
--      └─ Signed URL pre-authorises the request; RLS is not evaluated.
--
-- The RLS INSERT policy below is a defence-in-depth measure for any direct
-- (non-signed-URL) uploads that may be added in the future.

-- ── 1. Create the bucket (idempotent) ────────────────────────────────────────
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'salon-covers',
  'salon-covers',
  true,                                           -- public: cover images are displayed to clients
  5242880,                                        -- 5 MB per file
  ARRAY['image/jpeg', 'image/png', 'image/webp', 'image/heic', 'image/heif']
)
ON CONFLICT (id) DO UPDATE
  SET public              = EXCLUDED.public,
      file_size_limit     = EXCLUDED.file_size_limit,
      allowed_mime_types  = EXCLUDED.allowed_mime_types;

-- ── 2. Public read (clients browse salon covers before booking) ───────────────
DROP POLICY IF EXISTS "salon_covers_public_read" ON storage.objects;
CREATE POLICY "salon_covers_public_read"
  ON storage.objects FOR SELECT
  TO public
  USING (bucket_id = 'salon-covers');

-- ── 3. Owner insert — defence-in-depth for direct (non-signed-URL) uploads ───
-- Path convention: {salonId}/cover_{timestamp}.jpg
-- First folder segment must be a salon owned by the authenticated user.
DROP POLICY IF EXISTS "salon_covers_owner_insert" ON storage.objects;
CREATE POLICY "salon_covers_owner_insert"
  ON storage.objects FOR INSERT
  TO authenticated
  WITH CHECK (
    bucket_id = 'salon-covers'
    AND (storage.foldername(name))[1] IN (
      SELECT id::text FROM public.salons WHERE owner_id = auth.uid()
    )
  );

-- ── 4. Owner update (upsert / replace existing cover) ────────────────────────
DROP POLICY IF EXISTS "salon_covers_owner_update" ON storage.objects;
CREATE POLICY "salon_covers_owner_update"
  ON storage.objects FOR UPDATE
  TO authenticated
  USING (
    bucket_id = 'salon-covers'
    AND (storage.foldername(name))[1] IN (
      SELECT id::text FROM public.salons WHERE owner_id = auth.uid()
    )
  )
  WITH CHECK (
    bucket_id = 'salon-covers'
    AND (storage.foldername(name))[1] IN (
      SELECT id::text FROM public.salons WHERE owner_id = auth.uid()
    )
  );

-- ── 5. Owner delete ───────────────────────────────────────────────────────────
DROP POLICY IF EXISTS "salon_covers_owner_delete" ON storage.objects;
CREATE POLICY "salon_covers_owner_delete"
  ON storage.objects FOR DELETE
  TO authenticated
  USING (
    bucket_id = 'salon-covers'
    AND (storage.foldername(name))[1] IN (
      SELECT id::text FROM public.salons WHERE owner_id = auth.uid()
    )
  );

-- ── 6. Service role bypass (backend admin operations) ────────────────────────
-- The service role key is used in NestJS to generate signed upload URLs.
-- This policy ensures any other server-side storage operations also work.
DROP POLICY IF EXISTS "salon_covers_service_role_all" ON storage.objects;
CREATE POLICY "salon_covers_service_role_all"
  ON storage.objects FOR ALL
  TO service_role
  USING (bucket_id = 'salon-covers')
  WITH CHECK (bucket_id = 'salon-covers');
